quarkus:
  swagger-ui:
    always-include: true

  http:
    cors:
      ~: true
      methods: GET,POST
      origins: "/.*/"
    limits:
      max-body-size: 10M
    ssl:
      certificate:
        files: ssl/cert.pem
        key-files: ssl/key.pem

  container-image:
    group: openepcis
    name: quarkus-converter-service-ce
    additional-tags:
      - latest

  index-dependency:
    joda-time:
      group-id: joda-time
      artifact-id: joda-time

  locales: en
  default-locale: en-US
  banner:
    path: "openepcis-banner.txt"

  package:
    type: "uber-jar"

  native:
#    additional-build-args: "--initialize-at-build-time=io.openepcis.quarkus.model.OpenEPCISJAXBContextProducer"
#    additional-build-args: "--trace-object-instantiation=java.security.SecureRandom\\,java.rmi.server.ObjID\\,org.eclipse.persistence.internal.sessions.coordination.jms.JMSTopicRemoteConnection,-H:+UnlockExperimentalVMOptions,--initialize-at-build-time=java.rmi.server.ObjID\\,java.security.SecureRandom,--initialize-at-run-time=sun.rmi.transport.DGCImpl\\,org.eclipse.persistence.sessions.coordination.jms.JMSPublishingTransportManager\\,org.eclipse.persistence.internal.sessions.coordination.jms.JMSTopicRemoteConnection\\,io.openepcis.epc.converter.common.VersionTransformerProducer\\,org.apache.commons.math3.random.RandomDataGenerator\\,io.openepcis.testdata.generator.format.RandomValueGenerator,-H:-LocalizationOptimizedMode,-Duser.country=US,-Duser.language=en,-H:IncludeLocales=en,-H:IncludeResourceBundles=jakarta.xml.bind.Messages,-H:ReflectionConfigurationFiles=reflection-config.json,-H:-UnlockExperimentalVMOptions"
#    additional-build-args: "--trace-object-instantiation=java.security.SecureRandom\\,java.rmi.server.ObjID\\,org.eclipse.persistence.internal.sessions.coordination.jms.JMSTopicRemoteConnection,-H:+UnlockExperimentalVMOptions,--initialize-at-run-time=sun.rmi.transport.Transport\\,sun.rmi.transport.DGCClient\\,sun.rmi.transport.tcp.TCPEndpoint\\,java.rmi.server.ObjID\\,java.security.SecureRandom\\,sun.rmi.transport.DGCImpl\\,org.eclipse.persistence.sessions.coordination.jms.JMSPublishingTransportManager\\,org.eclipse.persistence.internal.sessions.coordination.jms.JMSTopicRemoteConnection,-H:-LocalizationOptimizedMode,-Duser.country=US,-Duser.language=en,-H:IncludeLocales=en,-H:IncludeResourceBundles=jakarta.xml.bind.Messages,-H:-UnlockExperimentalVMOptions"
    resources:
      includes: "ssl/*,1.2/EPCIS/**,2.0/EPCIS/**,**/*.xsl,**/*.xsd,**/*.json"
#      ,static/**,jakarta/**/*.properties,**/jaxb.properties,META-INF/services/.*,META-INF/.*.kotlin_module$"

mp:
  openapi:
    filter: "io.openepcis.resources.oas.EPCISExampleOASFilter"
    extensions:
      smallrye:
        info:
          title: "OpenEPCIS Document Converter API Community Edition"
          version: "1.0.0"
          description: "Convert EPCIS events with ease."
          contact:
            email: "info@openepcis.io"
            name: "OpenEPCIS | benelog GmbH & Co. KG"
            url: "https://openepcis.io"
            license:
              name: "Apache 2.0"
              url: "http://www.apache.org/licenses/LICENSE-2.0.html"
